---
abstract: 'add static content support to Limper'
author:
  - 'Ashley Willis <ashley+perl@gitable.org>'
build_requires:
  Net::HTTP::Client: 0
  POSIX: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Limper-SendFile
provides:
  Limper:
    file: lib/Limper/SendFile.pm
    version: 0.001
  Limper::SendFile:
    file: lib/Limper/SendFile.pm
    version: 0.001
requires:
  File::Slurp: 0
  JSON: 0
  Limper: 0
  Time::Local: 0
  base: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  repository: https://gitable.org/ashley/limper-sendfile.git
version: 0.001
